version: "3.9"
services:
  postgres:
    image: postgres:15.4-alpine3.18
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sOmEpriVateSecrEt
      - POSTGRES_DB=chat

  redis:
    image: redis:7.2-alpine3.18

  server:
    image: eruhini2022/chat-server
    ports:
      - "8080:8080"
    volumes:
      - /var/www/chat.eruhini.top:/public
    environment:
      - DATABASE_URL=postgres://root:sOmEpriVateSecrEt@postgres:5432/chat
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
    external: true
